package org.endeavourhealth.imapi.model;

import com.fasterxml.jackson.annotation.*;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include= JsonTypeInfo.As.PROPERTY, property="conceptType")
@JsonSubTypes({
    @JsonSubTypes.Type(value= Concept.class, name="Class"),
    @JsonSubTypes.Type(value= ObjectProperty.class, name="ObjectProperty"),
    @JsonSubTypes.Type(value= DataProperty.class, name="DataProperty"),
    @JsonSubTypes.Type(value= DataType.class, name="DataType"),
    @JsonSubTypes.Type(value= AnnotationProperty.class, name="Annotation")})
@JsonPropertyOrder({"conceptType","status","version","isRef","iri","name","description",
        "code","scheme","annotations","expression","subClassOf",",equivalentTo","DisjointWith","isA","containedIn"
   ,"property"})
public class Concept implements IMAnnotated {
    private Integer dbid;
    private String iri;
    private String name;
    private String description;
    private String code;
    private ConceptReference scheme;
    private ConceptStatus status;
    private Integer version;
    private Set<ConceptReference> isA;
    private Set<Annotation> annotations;
    private ConceptType conceptType;
    private Set<ClassExpression> subClassOf;
    private Set<ClassExpression> equivalentTo;
    private ClassExpression expression;
    private Set<ConceptReference> DisjointWith;
    private List<TermCode> synonym;
    private List<ConceptReference> containedIn;
    private boolean isRef;
    private List<PropertyConstraint> property;
    private List<ClassExpression> member;
    private List<Concept> memberExpansion;
    
    @JsonProperty("Expansion")
    public List<Concept> getExpansion() {
        return memberExpansion;
    }

    public Concept setExpansion(List<Concept> memberExpansion) {
        this.memberExpansion = memberExpansion;
        return this;
    }
    public Concept addExpansion (Concept memberExpansion){
        if (this.memberExpansion==null)
            this.memberExpansion= new ArrayList<>();
        this.memberExpansion.add(memberExpansion);
        return this;
    }

    @JsonProperty("Member")
    public List<ClassExpression> getMember() {
        return member;
    }

    public Concept setMember(List<ClassExpression> member) {
        this.member = member;
        return this;
    }
    public Concept addMember (ClassExpression expression){
        if (this.member==null)
            this.member= new ArrayList<>();
        member.add(expression);
        return this;
    }
    


    /**
     * Alternative constructor passing in the preferred concept type
     * @param conceptType
     */
    public Concept(ConceptType conceptType){
        this.setConceptType(conceptType);
    }

    public Concept() {
        this.setConceptType(ConceptType.CLASSONLY);
    }

    @Override
    public Integer getDbid() {
        return dbid;
    }

    @Override
    public Concept setDbid(Integer dbid) {
        this.dbid = dbid;
        return this;
    }


    @Override
    public ConceptStatus getStatus() {
        return status;
    }

    @Override
    public Concept setStatus(ConceptStatus status) {
        this.status=status;
        return this;
    }

    @Override
    public Integer getVersion() {
        return version;
    }

    @Override
    public Concept setVersion(Integer version) {
        this.version= version;
        return this;
    }



    public Concept(String iri, String name) {
        this.iri = iri;
        this.name = name;
    }

    public String getIri() {
        return iri;
    }

    public Concept setIri(String iri) {
        this.iri = iri;
        return this;
    }



    public String getName() {
        return name;
    }

    public Concept setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public Concept setDescription(String description) {
        this.description = description;
        return this;
    }

    public ConceptReference getScheme() {
        return scheme;
    }

    @JsonSetter
    public Concept setScheme(ConceptReference scheme) {
        this.scheme = scheme;
        return this;
    }

    public Concept setScheme(String scheme) {
        this.scheme = new ConceptReference(scheme);
        return this;
    }

    public String getCode() {
        return code;
    }

    public Concept setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Returns a list of IRIs which are the direct superconcepts of this concept
     * <p>This may include asserted superclasses and super properties and equivalent classes as well as those generated by a reasoner</p>
     * @return list of super concepts
     */
    @JsonProperty("IsA")
    public Set<ConceptReference> getIsA() {
        return isA;
    }

    public Concept setIsA(Set<ConceptReference> isA) {
        this.isA = isA;
        return this;
    }
    public Concept addIsa(ConceptReference isa){
        if (this.isA==null)
            isA= new HashSet<>();
        isA.add(isa);
        return this;
    }

    @JsonProperty("annotations")
    public Set<Annotation> getAnnotations() {
        return annotations;
    }

    public Concept setAnnotations(Set<Annotation> annotations) {
        this.annotations = annotations;
        return this;
    }
    public Concept addAnnotation(Annotation annotation) {
        if (this.annotations==null)
            this.annotations= new HashSet<>();
        this.annotations.add(annotation);
        return this;
    }



    @JsonProperty("conceptType")
    @JsonIgnore
    public ConceptType getConceptType() {
        return conceptType;
    }

    @JsonIgnore
    public Concept setConceptType(ConceptType conceptType) {
        this.conceptType = conceptType;
        return this;
    }
    @JsonProperty("DisjointWith")
    public Set<ConceptReference> getDisjointWith() {
        return DisjointWith;
    }

    public Concept setDisjointWith(Set<ConceptReference> DisjointWith) {
        this.DisjointWith = DisjointWith;
        return this;
    }
    public Concept addDisjointWith(ConceptReference iri) {
        if (this.DisjointWith == null)
            this.DisjointWith = new HashSet<>();
        this.DisjointWith.add(iri);
        return this;
    }

    public Concept addDisjointWith(String iri) {
        if (this.DisjointWith == null)
            this.DisjointWith = new HashSet<>();
        this.DisjointWith.add(new ConceptReference(iri));
        return this;
    }

    @JsonProperty("Expression")
    public ClassExpression getExpression(){
        return expression;
    }
    public Concept setExpression(ClassExpression cex){
        this.expression = cex;
        return this;
    }

    @JsonProperty("SubClassOf")
    public Set<ClassExpression> getSubClassOf() {
        return subClassOf;
    }

    public Concept setSubClassOf(Set<ClassExpression> subClassOf) {
        this.subClassOf = subClassOf;
        return this;
    }

    public Concept addSubClassOf(ClassExpression subClassOf) {
        if (this.subClassOf == null)
            this.subClassOf = new HashSet<>();

        this.subClassOf.add(subClassOf);
        return this;
    }

    @JsonProperty("EquivalentTo")
    public Set<ClassExpression> getEquivalentTo() {
        return equivalentTo;
    }

    public Concept setEquivalentTo(Set<ClassExpression> equivalentTo) {
        this.equivalentTo = equivalentTo;
        return this;
    }

    public Concept addEquivalentTo(ClassExpression equivalentTo) {
        if (this.equivalentTo == null)
            this.equivalentTo = new HashSet<>();
        this.equivalentTo.add(equivalentTo);
        return this;
    }

    public List<TermCode> getSynonym() {
        return synonym;
    }

    public Concept setSynonym(List<TermCode> synonym) {
        this.synonym = synonym;
        return this;
    }
    public Concept addSynonym(TermCode synonym){
        if (this.synonym==null)
            this.synonym= new ArrayList<>();
        this.synonym.add(synonym);
        return this;
    }

    @JsonProperty("isRef")
    public boolean isRef() {
        return isRef;
    }

    public Concept setRef(boolean ref) {
        isRef = ref;
        return this;
    }

    public List<ConceptReference> getContainedIn() {
        return containedIn;
    }

    public Concept setContainedIn(List<ConceptReference> containedIn) {
        this.containedIn = containedIn;
        return this;
    }
    public Concept addContainedIn(ConceptReference container){
        if (this.containedIn==null)
            this.containedIn= new ArrayList<>();
        this.containedIn.add(container);
        return this;
    }
   

    @JsonProperty("Property")
    public List<PropertyConstraint> getProperty() {
        return property;
    }

    public Concept setProperty(List<PropertyConstraint> property) {
        this.property = property;
        return this;
    }
    public Concept addProperty(PropertyConstraint property){
        if (this.property==null)
            this.property= new ArrayList<>();
        this.property.add(property);
        return this;
    }
}
