version: 0.0
os: linux
files:
  - source: /api/target/api-0.0.1-SNAPSHOT
    destination: {DESTINATION}
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
