version: 0.0
os: linux
files:
  - source: /api/build/libs/imapi.war
    destination: /opt/tomcat/webapps
  - source: /node_api/dist/*
    destination: /opt/nodeapi/
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
