version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - export CERT_FILE="s3://endeavour-deployment/InformationModel(v2)/casdoor-cert-${ENV}.txt"
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp $CERT_FILE ./src/main/java/resources/casdoor-cert.txt
      - pwd
      - ls -lrt ./src/main/java/resources/
      - chmod +x aws_scripts/build.sh
      - aws_scripts/build.sh IMAPI 1.0.0
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/cleanup
    - build/libs/imapi.war


