version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Fix iptables
      - update-alternatives --set iptables /usr/sbin/iptables-legacy
      - echo Start docker daemon
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Docker check
      - docker version
  build:
    commands:
      - echo Build started on `date`
      - chmod +x aws_scripts/build.sh
      - aws_scripts/build.sh mvn -B package
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/**/*
    - target/IMAPI.war
