spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/im_next
spring.datasource.username=imviewer
spring.datasource.password=imviewer
spring.jackson.serialization.fail-on-empty-beans=false

concept.datamodel.iri=:DiscoveryCommonDataModel
concept.isa.iri=sn:116680003