// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class BNF {
    public static final String DOMAIN = "http://bnf.info/";
    public static final String NAMESPACE = BNF.DOMAIN + "bnf#";
}
