// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class CODE_TEMPLATE {
  public static final String DOMAIN = "http://endhealth.info/";
  public static final String NAMESPACE = CODE_TEMPLATE.DOMAIN + "codeTemplate#";
  public static final String PREFIX = "cTemp";
  public static final String WRAPPER = CODE_TEMPLATE.NAMESPACE + "wrapper";
  public static final String DATATYPE_MAP = CODE_TEMPLATE.NAMESPACE + "datatypeMap";
  public static final String EXTENSION = CODE_TEMPLATE.NAMESPACE + "extension";
}
