// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class COMPONENT {
    public static final String DOMAIN = "http://endhealth.info/im#";
    public static final String NAMESPACE = COMPONENT.DOMAIN + "Component_";
    public static final String TEXT_DISPLAY = COMPONENT.NAMESPACE + "textDisplay";
    public static final String TEXT_INPUT = COMPONENT.NAMESPACE + "textInput";
    public static final String HTML_INPUT = COMPONENT.NAMESPACE + "htmlInput";
    public static final String ENTITY_MULTI_SEARCH = COMPONENT.NAMESPACE + "entityMultiSearch";
    public static final String ENTITY_SEARCH = COMPONENT.NAMESPACE + "entitySearch";
    public static final String ENTITY_COMBOBOX = COMPONENT.NAMESPACE + "entityComboBox";
    public static final String ENTITY_DROPDOWN = COMPONENT.NAMESPACE + "entityDropdown";
    public static final String ARRAY_BUILDER = COMPONENT.NAMESPACE + "arrayBuilder";
    public static final String ENTITY_AUTO_COMPLETE = COMPONENT.NAMESPACE + "entityAutoComplete";
    public static final String MEMBERS_BUILDER = COMPONENT.NAMESPACE + "membersBuilder";
    public static final String COMPONENT_GROUP = COMPONENT.NAMESPACE + "componentGroup";
    public static final String PROPERTY_BUILDER = COMPONENT.NAMESPACE + "propertyBuilder";
    public static final String SET_DEFINITION_BUILDER = COMPONENT.NAMESPACE + "SetDefinitionBuilder";
    public static final String QUERY_DEFINITION_BUILDER = COMPONENT.NAMESPACE + "QueryDefinitionBuilder";
    public static final String TOGGLEABLE = COMPONENT.NAMESPACE + "ToggleableComponent";
    public static final String HORIZONTAL_LAYOUT = COMPONENT.NAMESPACE + "HorizontalLayout";
    public static final String VERTICAL_LAYOUT = COMPONENT.NAMESPACE + "VerticalLayout";
    public static final String DROPDOWN_TEXT_INPUT_CONCATENATOR = COMPONENT.NAMESPACE + "dropdownTextInputConcatenator";
    public static final String ROLE_GROUP_BUILDER = COMPONENT.NAMESPACE + "roleGroupBuilder";
    public static final String TERM_CODE_EDITOR = COMPONENT.NAMESPACE + "termCodeEditor";
    public static final String TEXT_DROPDOWN = COMPONENT.NAMESPACE + "textDropdown";
    public static final String ENTITY_DISPLAY = COMPONENT.NAMESPACE + "entityDisplay";
    public static final String IRI_BUILDER = COMPONENT.NAMESPACE + "iriBuilder";
    public static final String AUTOCOMPLETE_SEARCH_BAR_WRAPPER = COMPONENT.NAMESPACE + "autocompleteSearchBarWrapper";
    public static final String SUBSET_BUILDER = COMPONENT.NAMESPACE + "subsetBuilder";
    public static final String DATASET_BUILDER = COMPONENT.NAMESPACE + "datasetQueryBuilder";
}
