// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class CONFIG {
    public static final String NAMESPACE = "http://endhealth.info/config#";
    public static final String DOMAIN = "http://endhealth.info/";
    public static final String PREFIX = "cfg";
    public static final String DEFINITION = CONFIG.NAMESPACE + "definition";
    public static final String SUMMARY = CONFIG.NAMESPACE + "summary";
    public static final String FILTER_DEFAULTS = CONFIG.NAMESPACE + "filterDefaults";
    public static final String INFERRED_PREDICATES = CONFIG.NAMESPACE + "inferredPredicates";
    public static final String INFERRED_EXCLUDE_PREDICATES = CONFIG.NAMESPACE + "inferredExcludePredicates";
    public static final String CONCEPT_DASHBOARD = CONFIG.NAMESPACE + "conceptDashboard";
    public static final String DEFAULT_PREDICATE_NAMES = CONFIG.NAMESPACE + "defaultPredicateNames";
    public static final String XML_SCHEMA_DATA_TYPES = CONFIG.NAMESPACE + "xmlSchemaDataTypes";
    public static final String DEFAULT_PREFIXES = CONFIG.NAMESPACE + "defaultPrefixes";
    public static final String GRAPH_EXCLUDE_PREDICATES = CONFIG.NAMESPACE + "graphExcludePredicates";
    public static final String IM1_PUBLISH = CONFIG.NAMESPACE + "im1Publish";
    public static final String IMDIRECTORY_LATEST_RELEASE = CONFIG.NAMESPACE + "IMDirectoryLatestRelease";
    public static final String IMDIRECTORY_ALL_RELEASES = CONFIG.NAMESPACE + "IMDirectoryAllReleases";
    public static final String IMPORT_DATA_LATEST_RELEASE = CONFIG.NAMESPACE + "ImportDataLatestRelease";
    public static final String IMPORT_DATA_ALL_RELEASES = CONFIG.NAMESPACE + "ImportDataAllReleases";
}
