// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class CONFIG {
    public static final String NAMESPACE = "http://endhealth.info/config#";
    public static final String DOMAIN = "http://endhealth.info/";
    public static final String PREFIX = "cfg";
    public static final String IMDIRECTORY_LATEST_RELEASE = CONFIG.NAMESPACE + "IMDirectoryLatestRelease";
    public static final String IMDIRECTORY_ALL_RELEASES = CONFIG.NAMESPACE + "IMDirectoryAllReleases";
    public static final String MONITORING = CONFIG.NAMESPACE + "monitoring";
}
