// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class FHIR {

	public static final String DOMAIN = "http://hl7.org/fhir/";
	public static final String PREFIX = "fhir";
	public static final String DSTU2 = "http://hl7.org/2-0/fhir/StructureDefinition#";
	public static final String GRAPH_FHIR = FHIR.DOMAIN;
	public static final String VALUESET_FOLDER = "http://endhealth.info/im#VSET_FHIR";
}