// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class IM_FUNCTION {
  public static final String DOMAIN = "http://endhealth.info/";
  public static final String NAMESPACE = IM_FUNCTION.DOMAIN + "im#Function_";
  public static final String SNOMED_CONCEPT_GENERATOR = IM_FUNCTION.NAMESPACE + "SnomedConceptGenerator";
  public static final String LOCAL_NAME_RETRIEVER = IM_FUNCTION.NAMESPACE + "LocalNameRetriever";
  public static final String GET_ADDITIONAL_ALLOWABLE_TYPES = IM_FUNCTION.NAMESPACE + "GetAdditionalAllowableTypes";
  public static final String GET_LOGIC_OPTIONS = IM_FUNCTION.NAMESPACE + "GetLogicOptions";
  public static final String GET_SET_EDITOR_IRI_SCHEMES = IM_FUNCTION.NAMESPACE + "GetSetEditorIriSchemes";
  public static final String IM1_SCHEME_OPTIONS = IM_FUNCTION.NAMESPACE + "IM1SchemeOptions";
  public static final String SCHEME_FROM_IRI = IM_FUNCTION.NAMESPACE + "SchemeFromIri";
  public static final String GET_USER_EDITABLE_SCHEMES = IM_FUNCTION.NAMESPACE + "GetUserEditableSchemes";
  public static final String GENERATE_IRI_CODE = IM_FUNCTION.NAMESPACE + "GenerateIriCode";
  public static final String IS_TYPE = IM_FUNCTION.NAMESPACE + "IsType";
  public static final String ALLOWABLE_PROPERTIES = IM_FUNCTION.NAMESPACE + "AllowableProperties";
  public static final String ALLOWABLE_RANGES = IM_FUNCTION.NAMESPACE + "AllowableRanges";
  public static final String ALLOWABLE_PROPERTY_VALUES = IM_FUNCTION.NAMESPACE + "AllowablePropertyValues";
}
