// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class MAP {

	public static final String DOMAIN = "http://endhealth.info/";
	public static final String NAMESPACE = MAP.DOMAIN + "map#";
	public static final String PREFIX = "map";
}