// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class ORG {
    public static final String ORGANISATION_NAMESPACE = "http://org.endhealth.info/im#";
    public static final String LOCATION_NAMESPACE = "http://loc.endhealth.info/im#";
    public static final String ORGANISATION_RECORD_CLASS = "http://endhealth.info/im#organisationRecordClass";
    public static final String RELATED_ORGANISATION = "http://endhealth.info/im#organisationRelationship";
    public static final String TARGET = "http://endhealth.info/im#targetOrganisation";
    public static final String ROLE = "http://endhealth.info/im#organisationRole";
    public static final String ODS_CODE = "http://endhealth.info/im#odsCode";
}
