// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class OWL {
    public static final String NAMESPACE = "http://www.w3.org/2002/07/owl#";
    public static final String PREFIX = "owl";
    public static final String THING = OWL.NAMESPACE + "Thing";
    public static final String CLASS = OWL.NAMESPACE + "Class";
    public static final String EQUIVALENT_CLASS = OWL.NAMESPACE + "equivalentClass";
    public static final String INTERSECTION_OF = OWL.NAMESPACE + "intersectionOf";
    public static final String UNION_OF = OWL.NAMESPACE + "unionOf";
    public static final String RESTRICTION = OWL.NAMESPACE + "Restriction";
    public static final String ON_PROPERTY = OWL.NAMESPACE + "onProperty";
    public static final String ON_CLASS = OWL.NAMESPACE + "onClass";
    public static final String SOME_VALUES_FROM = OWL.NAMESPACE + "someValuesFrom";
    public static final String ALL_VALUES_FROM = OWL.NAMESPACE + "allValuesFrom";
    public static final String OBJECT_PROPERTY = OWL.NAMESPACE + "ObjectProperty";
    public static final String DATATYPE_PROPERTY = OWL.NAMESPACE + "DatatypeProperty";
    public static final String ANNOTATION_PROPERTY = OWL.NAMESPACE + "AnnotationProperty";
    public static final String INVERSE_OF = OWL.NAMESPACE + "inverseOf";
    public static final String INVERSE_OBJECT_PROPERTY = OWL.NAMESPACE + "inverseOf";
    public static final String PROPERTY_CHAIN = OWL.NAMESPACE + "propertyChainAxiom";
    public static final String TRANSITIVE = OWL.NAMESPACE + "TransitiveProperty";
    public static final String FUNCTIONAL = OWL.NAMESPACE + "FunctionalProperty";
    public static final String SYMMETRIC = OWL.NAMESPACE + "SymmetricProperty";
    public static final String REFLEXIVE = OWL.NAMESPACE + "ReflexiveProperty";
    public static final String ON_DATATYPE = OWL.NAMESPACE + "onDatatype";
    public static final String WITH_RESTRICTIONS = OWL.NAMESPACE + "withRestrictions";
    public static final String MAX_CARDINALITY = OWL.NAMESPACE + "maxCardinality";
    public static final String MIN_CARDINALITY = OWL.NAMESPACE + "minCardinality";
    public static final String ON_DATA_RANGE = OWL.NAMESPACE + "onDataRange";
    public static final String HAS_VALUE = OWL.NAMESPACE + "hasValue";
    public static final String COMPLEMENT_OF = OWL.NAMESPACE + "complementOf";
    public static final String ONE_OF = OWL.NAMESPACE + "oneOf";
    public static final String NAMED_INDIVIDUAL = OWL.NAMESPACE + "NamedIndividual";
}
