// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class PRSB {
    public static final String NAMESPACE = "http://prsb.info/rs#";
    public static final String PREFIX = "rs";
}
