// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class RDF {
	public static final String NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
	public static final String PREFIX = "rdf";
	public static final String TYPE = RDF.NAMESPACE + "type";
	public static final String PROPERTY = RDF.NAMESPACE + "Property";
	public static final String LIST = RDF.NAMESPACE + "List";
	public static final String PREDICATE = RDF.NAMESPACE + "predicate";
	public static final String SUBJECT = RDF.NAMESPACE + "subject";
	public static final String OBJECT = RDF.NAMESPACE + "object";
}