// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class RDFS {
  public static final String NAMESPACE = "http://www.w3.org/2000/01/rdf-schema#";
  public static final String PREFIX = "rdfs";
  public static final String LABEL = RDFS.NAMESPACE + "label";
  public static final String COMMENT = RDFS.NAMESPACE + "comment";
  public static final String SUBCLASS_OF = RDFS.NAMESPACE + "subClassOf";
  public static final String SUB_PROPERTY_OF = RDFS.NAMESPACE + "subPropertyOf";
  public static final String DOMAIN = RDFS.NAMESPACE + "domain";
  public static final String RANGE = RDFS.NAMESPACE + "range";
  public static final String RESOURCE = RDFS.NAMESPACE + "Resource";
  public static final String CLASS = RDFS.NAMESPACE + "Class";
  public static final String DATATYPE = RDFS.NAMESPACE + "Datatype";
  public static final String IS_DEFINED_BY = RDFS.NAMESPACE + "isDefinedBy";
}
