// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class SHACL {
    public static final String NAMESPACE = "http://www.w3.org/ns/shacl#";
    public static final String PREFIX = "sh";
    public static final String PATH = SHACL.NAMESPACE + "path";
    public static final String MININCLUSIVE = SHACL.NAMESPACE + "minInclusive";
    public static final String MINEXCLUSIVE = SHACL.NAMESPACE + "minExclusive";
    public static final String MAXINCLUSIVE = SHACL.NAMESPACE + "maxInclusive";
    public static final String MAXEXCLUSIVE = SHACL.NAMESPACE + "maxExclusive";
    public static final String PROPERTY = SHACL.NAMESPACE + "property";
    public static final String PROPERTY_GROUP = SHACL.NAMESPACE + "PropertyGroup";
    public static final String MINCOUNT = SHACL.NAMESPACE + "minCount";
    public static final String MAXCOUNT = SHACL.NAMESPACE + "maxCount";
    public static final String VALUE = SHACL.NAMESPACE + "value";
    public static final String PATTERN = SHACL.NAMESPACE + "pattern";
    public static final String INVERSEPATH = SHACL.NAMESPACE + "inversePath";
    public static final String CLASS = SHACL.NAMESPACE + "class";
    public static final String DATATYPE = SHACL.NAMESPACE + "datatype";
    public static final String SPARQL = SHACL.NAMESPACE + "sparql";
    public static final String SELECT = SHACL.NAMESPACE + "select";
    public static final String PARAMETER = SHACL.NAMESPACE + "parameter";
    public static final String IRI = SHACL.NAMESPACE + "IRI";
    public static final String OPTIONAL = SHACL.NAMESPACE + "optional";
    public static final String NODESHAPE = SHACL.NAMESPACE + "NodeShape";
    public static final String TARGETCLASS = SHACL.NAMESPACE + "targetClass";
    public static final String NODE = SHACL.NAMESPACE + "node";
    public static final String ORDER = SHACL.NAMESPACE + "order";
    public static final String OR = SHACL.NAMESPACE + "or";
    public static final String NOT = SHACL.NAMESPACE + "not";
    public static final String NODE_KIND = SHACL.NAMESPACE + "nodeKind";
    public static final String PROPERTYSHAPE = SHACL.NAMESPACE + "PropertyShape";
    public static final String AND = SHACL.NAMESPACE + "and";
    public static final String NODES = SHACL.NAMESPACE + "nodes";
    public static final String TARGET_TYPE = SHACL.NAMESPACE + "targetType";
    public static final String TARGET = SHACL.NAMESPACE + "target";
    public static final String SPARQL_TARGET = SHACL.NAMESPACE + "SPARQLTarget";
    public static final String FUNCTION = SHACL.NAMESPACE + "FunctionClause";
    public static final String RETURN_TYPE = SHACL.NAMESPACE + "returnType";
    public static final String GROUP = SHACL.NAMESPACE + "group";
    public static final String NAME = SHACL.NAMESPACE + "name";
    public static final String EXPRESSION = SHACL.NAMESPACE + "expression";
    public static final String HAS_VALUE = SHACL.NAMESPACE + "hasValue";
}
