// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class SNOMED {

	public static final String DOMAIN = "http://snomed.info/";
	public static final String NAMESPACE = SNOMED.DOMAIN + "sct#";
	public static final String PREFIX = "sn";
	public static final String ATTRIBUTE = SNOMED.DOMAIN + "246061005";
}