// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class VALIDATION {
	public static final String DOMAIN = "http://endhealth.info/im#";
	public static final String NAMESPACE = VALIDATION.DOMAIN + "Validation_";
	public static final String IS_DEFINITION = VALIDATION.NAMESPACE + "isDefinition";
	public static final String HAS_PARENT = VALIDATION.NAMESPACE + "hasParent";
	public static final String IS_IRI = VALIDATION.NAMESPACE + "isIri";
	public static final String IS_TERMCODE = VALIDATION.NAMESPACE + "isTermcode";
	public static final String IS_PROPERTY = VALIDATION.NAMESPACE + "isProperty";
	public static final String IS_SCHEME = VALIDATION.NAMESPACE + "isScheme";
	public static final String IS_STATUS = VALIDATION.NAMESPACE + "isStatus";
	public static final String IS_ROLE_GROUP = VALIDATION.NAMESPACE + "isRoleGroup";
}