// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class WORKFLOW {
	public static final String DOMAIN = "http://endhealth.info/";
	public static final String NAMESPACE = WORKFLOW.DOMAIN + "workflow#";
	public static final String BUG_REPORT = WORKFLOW.NAMESPACE + "bugReport";
	public static final String DATE_CREATED = WORKFLOW.NAMESPACE + "dateCreated";
	public static final String CREATED_BY = WORKFLOW.NAMESPACE + "createdBy";
	public static final String ASSIGNED_TO = WORKFLOW.NAMESPACE + "assignedTo";
	public static final String STATE = WORKFLOW.NAMESPACE + "state";
	public static final String RELATED_PRODUCT = WORKFLOW.NAMESPACE + "relatedProduct";
	public static final String RELATED_MODULE = WORKFLOW.NAMESPACE + "relatedModule";
	public static final String OPERATING_SYSTEM = WORKFLOW.NAMESPACE + "operatingSystem";
	public static final String BROWSER = WORKFLOW.NAMESPACE + "browser";
	public static final String SEVERITY = WORKFLOW.NAMESPACE + "severity";
	public static final String ERROR = WORKFLOW.NAMESPACE + "errorDetails";
	public static final String REPRODUCE_STEPS = WORKFLOW.NAMESPACE + "reproduceSteps";
	public static final String EXPECTED_RESULT = WORKFLOW.NAMESPACE + "expectedResult";
	public static final String ACTUAL_RESULT = WORKFLOW.NAMESPACE + "actualResult";
	public static final String RELATED_VERSION = WORKFLOW.NAMESPACE + "relatedVersion";
}