// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class XS {
    public static final String NAMESPACE = "http://www.w3.org/2001/XMLSchema#";
    public static final String PREFIX = "xs";
    public static final String PATTERN = XS.NAMESPACE + "pattern";
    public static final String MIN_INCLUSIVE = XS.NAMESPACE + "minInclusive";
    public static final String MIN_EXCLUSIVE = XS.NAMESPACE + "minExclusive";
    public static final String MAX_INCLUSIVE = XS.NAMESPACE + "maxInclusive";
    public static final String MAX_EXCLUSIVE = XS.NAMESPACE + "maxExclusive";
    public static final String INTEGER = XS.NAMESPACE + "integer";
    public static final String STRING = XS.NAMESPACE + "string";
    public static final String BOOLEAN = XS.NAMESPACE + "boolean";
    public static final String LONG = XS.NAMESPACE + "long";
    public static final String DOUBLE = XS.NAMESPACE + "double";
    public static final String DATE_TIME = XS.NAMESPACE + "dateTime";
}
