// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

package org.endeavourhealth.imapi.vocabulary;

public class XSD {
	public static final String NAMESPACE = "http://www.w3.org/2001/XMLSchema#";
	public static final String PREFIX = "xsd";
	public static final String PATTERN = XSD.NAMESPACE + "pattern";
	public static final String MININCLUSIVE = XSD.NAMESPACE + "minInclusive";
	public static final String MINEXCLUSIVE = XSD.NAMESPACE + "minExclusive";
	public static final String MAXINCLUSIVE = XSD.NAMESPACE + "maxInclusive";
	public static final String MAXEXCLUSIVE = XSD.NAMESPACE + "maxExclusive";
	public static final String INTEGER = XSD.NAMESPACE + "integer";
	public static final String STRING = XSD.NAMESPACE + "string";
	public static final String BOOLEAN = XSD.NAMESPACE + "boolean";
	public static final String LONG = XSD.NAMESPACE + "long";
	public static final String DOUBLE = XSD.NAMESPACE + "double";
}