"use strict";
exports.__esModule = true;
exports.SHACL = exports.RDFS = exports.RDF = exports.OWL = exports.IM = void 0;
var IM_1 = require("./IM");
exports.IM = IM_1.IM;
var OWL_1 = require("./OWL");
exports.OWL = OWL_1.OWL;
var RDF_1 = require("./RDF");
exports.RDF = RDF_1.RDF;
var RDFS_1 = require("./RDFS");
exports.RDFS = RDFS_1.RDFS;
var SHACL_1 = require("./SHACL");
exports.SHACL = SHACL_1.SHACL;
