// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum CodeTemplate implements VocabEnum {

    DOMAIN("http://endhealth.info/"),
    PREFIX("cTemp"),
    WRAPPER(Namespace.IM_CODE_TEMPLATE + "wrapper"),
    LABEL(RDFS.LABEL),
    DEFINITION(IM.DEFINITION),
    DATATYPE_MAP(Namespace.IM_CODE_TEMPLATE + "datatypeMap"),
    EXTENSION(Namespace.IM_CODE_TEMPLATE + "extension"),
    INCLUDE_COMPLEX_TYPES(Namespace.IM_CODE_TEMPLATE + "includeComplexTypes"),
    ;

    private final String value;

    CodeTemplate(final String value) {
        this.value = value;
    }

    CodeTemplate(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static CodeTemplate from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (CodeTemplate b : CodeTemplate.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
