// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum COMPONENT implements VocabEnum {

    DOMAIN("http://endhealth.info/im#"),
    NAMESPACE(COMPONENT.DOMAIN + "Component_"),
    TAB_LAYOUT(COMPONENT.NAMESPACE + "TabLayout"),
    TEXT_DISPLAY(COMPONENT.NAMESPACE + "textDisplay"),
    TEXT_INPUT(COMPONENT.NAMESPACE + "textInput"),
    HTML_INPUT(COMPONENT.NAMESPACE + "htmlInput"),
    ENTITY_MULTI_SEARCH(COMPONENT.NAMESPACE + "entityMultiSearch"),
    ENTITY_SEARCH(COMPONENT.NAMESPACE + "entitySearch"),
    ENTITY_COMBOBOX(COMPONENT.NAMESPACE + "entityComboBox"),
    ENTITY_DROPDOWN(COMPONENT.NAMESPACE + "entityDropdown"),
    ARRAY_BUILDER(COMPONENT.NAMESPACE + "arrayBuilder"),
    ENTITY_AUTO_COMPLETE(COMPONENT.NAMESPACE + "entityAutoComplete"),
    MEMBERS_BUILDER(COMPONENT.NAMESPACE + "membersBuilder"),
    COMPONENT_GROUP(COMPONENT.NAMESPACE + "componentGroup"),
    PROPERTY_BUILDER(COMPONENT.NAMESPACE + "propertyBuilder"),
    SET_DEFINITION_BUILDER(COMPONENT.NAMESPACE + "SetDefinitionBuilder"),
    QUERY_DEFINITION_BUILDER(COMPONENT.NAMESPACE + "QueryDefinitionBuilder"),
    TOGGLEABLE(COMPONENT.NAMESPACE + "ToggleableComponent"),
    HORIZONTAL_LAYOUT(COMPONENT.NAMESPACE + "HorizontalLayout"),
    VERTICAL_LAYOUT(COMPONENT.NAMESPACE + "VerticalLayout"),
    DROPDOWN_TEXT_INPUT_CONCATENATOR(COMPONENT.NAMESPACE + "dropdownTextInputConcatenator"),
    ROLE_GROUP_BUILDER(COMPONENT.NAMESPACE + "roleGroupBuilder"),
    TERM_CODE_EDITOR(COMPONENT.NAMESPACE + "termCodeEditor"),
    TEXT_DROPDOWN(COMPONENT.NAMESPACE + "textDropdown"),
    ENTITY_DISPLAY(COMPONENT.NAMESPACE + "entityDisplay"),
    IRI_BUILDER(COMPONENT.NAMESPACE + "iriBuilder"),
    AUTOCOMPLETE_SEARCH_BAR_WRAPPER(COMPONENT.NAMESPACE + "autocompleteSearchBarWrapper"),
    SUBSET_BUILDER(COMPONENT.NAMESPACE + "subsetBuilder"),
    ;

    private final String value;

    COMPONENT(final String value) {
        this.value = value;
    }

    COMPONENT(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static COMPONENT from(String text) {
    for (COMPONENT b : COMPONENT.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
