// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum EDITOR implements VocabEnum {

    DOMAIN("http://endhealth.info/im#"),
    NAMESPACE(EDITOR.DOMAIN + "Editor_"),
    CONCEPT_SHAPE(EDITOR.NAMESPACE + "ConceptShape"),
    CONCEPT_SET_SHAPE(EDITOR.NAMESPACE + "ConceptSetShape"),
    VALUE_SET_SHAPE(EDITOR.NAMESPACE + "ValueSetShape"),
    FOLDER_SHAPE(EDITOR.NAMESPACE + "FolderShape"),
    DATA_MODEL_SHAPE(EDITOR.NAMESPACE + "DataModelShape"),
    COHORT_QUERY_SHAPE(EDITOR.NAMESPACE + "CohortQueryShape"),
    PROPERTY_SHAPE(EDITOR.NAMESPACE + "PropertyShape"),
    ;

    private final String value;

    EDITOR(final String value) {
        this.value = value;
    }

    EDITOR(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static EDITOR from(String text) {
    for (EDITOR b : EDITOR.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
