// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum Graph implements VocabEnum {

    IM("http://endhealth.info/im#"),
    PROV("http://endhealth.info/prov#"),
    USER("http://endhealth.info/user#"),
    WORKFLOW("http://endhealth.info/workflow#"),
    CONFIG("http://endhealth.info/config#"),
    SMARTLIFE("http://smartlifehealth.info/smh#"),
    ;

    private final String value;

    Graph(final String value) {
        this.value = value;
    }

    Graph(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static Graph from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (Graph b : Graph.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
