// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

public class GRAPH {
    public static final String DISCOVERY = "http://endhealth.info/im#";
    public static final String PROV = "http://endhealth.info/prov#";
}
