// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum IM_FUNCTION implements VocabEnum {

    DOMAIN("http://endhealth.info/"),
    SNOMED_CONCEPT_GENERATOR(Namespace.FUNCTION + "SnomedConceptGenerator"),
    LOCAL_NAME_RETRIEVER(Namespace.FUNCTION + "LocalNameRetriever"),
    GET_ADDITIONAL_ALLOWABLE_TYPES(Namespace.FUNCTION + "GetAdditionalAllowableTypes"),
    GET_LOGIC_OPTIONS(Namespace.FUNCTION + "GetLogicOptions"),
    GET_SET_EDITOR_IRI_SCHEMES(Namespace.FUNCTION + "GetSetEditorIriSchemes"),
    IM1_SCHEME_OPTIONS(Namespace.FUNCTION + "IM1SchemeOptions"),
    SCHEME_FROM_IRI(Namespace.FUNCTION + "SchemeFromIri"),
    GET_USER_EDITABLE_SCHEMES(Namespace.FUNCTION + "GetUserEditableSchemes"),
    IS_TYPE(Namespace.FUNCTION + "IsType"),
    ALLOWABLE_PROPERTIES(Namespace.FUNCTION + "AllowableProperties"),
    ALLOWABLE_RANGES(Namespace.FUNCTION + "AllowableRanges"),
    ALLOWABLE_PROPERTY_VALUES(Namespace.FUNCTION + "AllowablePropertyValues"),
    ;

    private final String value;

    IM_FUNCTION(final String value) {
        this.value = value;
    }

    IM_FUNCTION(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static IM_FUNCTION from(String text) {
      for (IM_FUNCTION b : IM_FUNCTION.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      return null;
    }

}
