// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum IMPORT implements VocabEnum {

    CEG("ceg"),
    IM1("imv1"),
    QOF("qof"),
    QUERY("corequery"),
    BNF("bnf"),
    PRSB("prsb"),
    CORE("core"),
    SNOMED("snomed"),
    EMIS("emis"),
    CPRD_MED("cprd"),
    TPP("tpp"),
    OPCS4("opcs4"),
    ICD10("icd10"),
    ENCOUNTERS("encounters"),
    VISION("vision"),
    KINGS_APEX("kingsapex"),
    KINGS_WINPATH("kingswinpath"),
    SMARTLIFE("smartlifequery"),
    BARTS_CERNER("barts"),
    ODS("ods"),
    NHS_TFC("nhstfc"),
    CONFIG("config"),
    DELTAS("deltas"),
    SINGLE_FILE("singlefile"),
    QR("qcodegroups"),
    FHIR("fhir"),
    ;

    private final String value;

    IMPORT(final String value) {
        this.value = value;
    }

    IMPORT(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static IMPORT from(String text) {
      for (IMPORT b : IMPORT.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      return null;
    }

}
