// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum Namespace implements VocabEnum {

    CEG("http://endhealth.info/ceg#"),
    QOF("http://endhealth.info/qof#"),
    SMARTLIFE("http://smartlifehealth.info/smh#"),
    CONFIG("http://endhealth.info/config#"),
    IMQ("http://endhealth.info/imq#"),
    IM("http://endhealth.info/im#"),
    FUNCTION("http://endhealth.info/im#Function_"),
    MAP("http://endhealth.info/map#"),
    OWL("http://www.w3.org/2002/07/owl#"),
    PRSB("http://prsb.info/rs#"),
    BNF("http://bnf.info/bnf#"),
    QR("http://apiqcodes.org/qcodes#"),
    RDF("http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
    RDFS("http://www.w3.org/2000/01/rdf-schema#"),
    SHACL("http://www.w3.org/ns/shacl#"),
    SNOMED("http://snomed.info/sct#"),
    USER("http://endhealth.info/user#"),
    WORKFLOW("http://endhealth.info/workflow#"),
    XSD("http://www.w3.org/2001/XMLSchema#"),
    IM_COMPONENT("http://endhealth.info/im#Component_"),
    IM_EDITOR("http://endhealth.info/im#Editor_"),
    IM_QUERY("http://endhealth.info/im#Query_"),
    IM_VALIDATION("http://endhealth.info/im#Validation_"),
    IM_CODE_TEMPLATE("http://endhealth.info/im#codeTemplate#"),
    TPP("http://endhealth.info/tpp#"),
    ENCOUNTERS("http://endhealth.info/enc#"),
    ICD10("http://endhealth.info/icd10#"),
    VISION("http://endhealth.info/vis#"),
    OPCS4("http://endhealth.info/opcs4#"),
    BARTS_CERNER("http://endhealth.info/bc#"),
    ORGANISATION("http://org.endhealth.info/im#"),
    LOCATION("http://loc.endhealth.info/im#"),
    ;

    private final String value;

    Namespace(final String value) {
        this.value = value;
    }

    Namespace(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static Namespace from(String text) {
      for (Namespace b : Namespace.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      return null;
    }

}
