// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum OWL implements VocabEnum {

    PREFIX("owl"),
    THING(Namespace.OWL + "Thing"),
    CLASS(Namespace.OWL + "Class"),
    EQUIVALENT_CLASS(Namespace.OWL + "equivalentClass"),
    INTERSECTION_OF(Namespace.OWL + "intersectionOf"),
    UNION_OF(Namespace.OWL + "unionOf"),
    RESTRICTION(Namespace.OWL + "Restriction"),
    ON_PROPERTY(Namespace.OWL + "onProperty"),
    ON_CLASS(Namespace.OWL + "onClass"),
    SOME_VALUES_FROM(Namespace.OWL + "someValuesFrom"),
    ALL_VALUES_FROM(Namespace.OWL + "allValuesFrom"),
    OBJECT_PROPERTY(Namespace.OWL + "ObjectProperty"),
    DATATYPE_PROPERTY(Namespace.OWL + "DatatypeProperty"),
    ANNOTATION_PROPERTY(Namespace.OWL + "AnnotationProperty"),
    INVERSE_OF(Namespace.OWL + "inverseOf"),
    INVERSE_OBJECT_PROPERTY(Namespace.OWL + "inverseOf"),
    PROPERTY_CHAIN(Namespace.OWL + "propertyChainAxiom"),
    TRANSITIVE(Namespace.OWL + "TransitiveProperty"),
    FUNCTIONAL(Namespace.OWL + "FunctionalProperty"),
    SYMMETRIC(Namespace.OWL + "SymmetricProperty"),
    REFLEXIVE(Namespace.OWL + "ReflexiveProperty"),
    ON_DATATYPE(Namespace.OWL + "onDatatype"),
    WITH_RESTRICTIONS(Namespace.OWL + "withRestrictions"),
    MAX_CARDINALITY(Namespace.OWL + "maxCardinality"),
    MIN_CARDINALITY(Namespace.OWL + "minCardinality"),
    ON_DATA_RANGE(Namespace.OWL + "onDataRange"),
    HAS_VALUE(Namespace.OWL + "hasValue"),
    COMPLEMENT_OF(Namespace.OWL + "complementOf"),
    ONE_OF(Namespace.OWL + "oneOf"),
    NAMED_INDIVIDUAL(Namespace.OWL + "NamedIndividual"),
    ;

    private final String value;

    OWL(final String value) {
        this.value = value;
    }

    OWL(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static OWL from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (OWL b : OWL.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
