// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum QUERY implements VocabEnum {

    DOMAIN("http://endhealth.info/im#"),
    IS_ALLOWABLE_RANGE(Namespace.IM_QUERY + "IsAllowableRange"),
    ALLOWABLE_RANGE_SUGGESTIONS(Namespace.IM_QUERY + "AllowableRangeSuggestions"),
    GET_SUBCLASSES(Namespace.IM_QUERY + "GetSubClasses"),
    GET_ANCESTORS(Namespace.IM_QUERY + "GetAncestors"),
    SEARCH_CONTAINED_IN(Namespace.IM_QUERY + "SearchContainedIn"),
    ALLOWABLE_CHILD_TYPES(Namespace.IM_QUERY + "AllowableChildTypes"),
    PROPERTY_RANGE(Namespace.IM_QUERY + "PropertyRange"),
    OBJECT_PROPERTY_RANGE_SUGGESTIONS(Namespace.IM_QUERY + "ObjectPropertyRangeSuggestions"),
    DATA_PROPERTY_RANGE_SUGGESTIONS(Namespace.IM_QUERY + "DataPropertyRangeSuggestions"),
    ALLOWABLE_PROPERTIES(Namespace.IM_QUERY + "AllowableProperties"),
    ALLOWABLE_PROPERTY_ANCESTORS(Namespace.IM_QUERY + "AllowablePropertyAncestors"),
    IS_VALID_PROPERTY(Namespace.IM_QUERY + "IsValidProperty"),
    SEARCH_PROPERTIES(Namespace.IM_QUERY + "SearchProperties"),
    SEARCH_ENTITIES(Namespace.IM_QUERY + "SearchEntities"),
    SEARCH_FOLDERS(Namespace.IM_QUERY + "SearchFolders"),
    SEARCH_ALLOWABLE_CONTAINED_IN(Namespace.IM_QUERY + "SearchAllowableContainedIn"),
    SEARCH_MAIN_TYPES(Namespace.IM_QUERY + "SearchmainTypes"),
    DM_PROPERTY(Namespace.IM_QUERY + "DataModelPropertyByShape"),
    SEARCH_ALLOWABLE_SUBCLASS(Namespace.IM_QUERY + "SearchAllowableSubclass"),
    GET_VALUES_FROM_PROPERTY_RANGE(Namespace.IM_QUERY + "GetValuesFromPropertyRange"),
    GET_SUBSETS(Namespace.IM_QUERY + "GetSubsets"),
    ;

    private final String value;

    QUERY(final String value) {
        this.value = value;
    }

    QUERY(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static QUERY from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (QUERY b : QUERY.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
