// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum RDFS implements VocabEnum {

    NAMESPACE("http://www.w3.org/2000/01/rdf-schema#"),
    PREFIX("rdfs"),
    LABEL(RDFS.NAMESPACE + "label"),
    COMMENT(RDFS.NAMESPACE + "comment"),
    SUBCLASS_OF(RDFS.NAMESPACE + "subClassOf"),
    SUB_PROPERTY_OF(RDFS.NAMESPACE + "subPropertyOf"),
    DOMAIN(RDFS.NAMESPACE + "domain"),
    RANGE(RDFS.NAMESPACE + "range"),
    RESOURCE(RDFS.NAMESPACE + "Resource"),
    CLASS(RDFS.NAMESPACE + "Class"),
    DATATYPE(RDFS.NAMESPACE + "Datatype"),
    IS_DEFINED_BY(RDFS.NAMESPACE + "isDefinedBy"),
    ;

    private final String value;

    RDFS(final String value) {
        this.value = value;
    }

    RDFS(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static RDFS from(String text) {
    for (RDFS b : RDFS.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
