// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum SCHEME implements VocabEnum {

    SNOMED("http://snomed.info/sct#"),
    FHIR("http://hl7.org/fhir/"),
    SMARTLIFE("http://smartlifehealth.info/smh#"),
    QOF("http://endhealth.info/qof#"),
    IM("http://endhealth.info/im#"),
    BNF("http://bnf.info/bnf#"),
    ICD10("http://endhealth.info/icd10#"),
    EMIS("http://endhealth.info/emis#"),
    CPRD_MED("http://endhealth.info/cprdm#"),
    CPRD_PROD("http://endhealth.info/cprdp#"),
    OPCS4("http://endhealth.info/opcs4#"),
    TPP("http://endhealth.info/tpp#"),
    ODS("http://endhealth.info/ods#"),
    PRSB("http://endhealth.info/prsb#"),
    KINGS_APEX("http://endhealth.info/kpax#"),
    KINGS_WINPATH("http://endhealth.info/kwp#"),
    VISION("http://endhealth.info/vis#"),
    READ2("http://endhealth.info/read2#"),
    BARTS_CERNER("http://endhealth.info/bc#"),
    NHSDD_ETHNIC_2001("http://endhealth.info/nhsethnic2001#"),
    IM1("http://endhealth.info/im1#"),
    ENCOUNTERS("http://endhealth.info/enc#"),
    CONFIG("http://endhealth.info/config#"),
    CEG("http://endhealth.info/ceg#"),
    NHS_TFC("http://endhealth.info/nhstfc#"),
    STATS("http://endhealth.info/stats#"),
    DELTAS("http://endhealth.info/deltas#"),
    PROV("http://endhealth.info/prov#"),
    QUERY("http://endhealth.info/query#"),
    REPORTS("http://endhealth.info/reports#"),
    OPS_ROLES("https://directory.spineservices.nhs.uk/STU3/CodeSystem/ODSAPI-OrganizationRole-1#"),
    XS("http://www.w3.org/2001/XMLSchema#"),
    SYSTEM("http://sys.endhealth.info/im#"),
    QR("http://apiqcodes.org/qcodes#"),
    ;

    private final String value;

    SCHEME(final String value) {
        this.value = value;
    }

    SCHEME(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static SCHEME from(String text) {
      for (SCHEME b : SCHEME.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      return null;
    }

}
