// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum SHACL implements VocabEnum {

    PREFIX("sh"),
    PATH(Namespace.SHACL + "path"),
    MININCLUSIVE(Namespace.SHACL + "minInclusive"),
    MINEXCLUSIVE(Namespace.SHACL + "minExclusive"),
    MAXINCLUSIVE(Namespace.SHACL + "maxInclusive"),
    MAXEXCLUSIVE(Namespace.SHACL + "maxExclusive"),
    PROPERTY(Namespace.SHACL + "property"),
    PROPERTY_GROUP(Namespace.SHACL + "PropertyGroup"),
    MINCOUNT(Namespace.SHACL + "minCount"),
    MAXCOUNT(Namespace.SHACL + "maxCount"),
    VALUE(Namespace.SHACL + "value"),
    PATTERN(Namespace.SHACL + "pattern"),
    INVERSEPATH(Namespace.SHACL + "inversePath"),
    CLASS(Namespace.SHACL + "class"),
    DATATYPE(Namespace.SHACL + "datatype"),
    SPARQL(Namespace.SHACL + "sparql"),
    SELECT(Namespace.SHACL + "select"),
    PARAMETER(Namespace.SHACL + "parameter"),
    IRI(Namespace.SHACL + "IRI"),
    OPTIONAL(Namespace.SHACL + "optional"),
    NODESHAPE(Namespace.SHACL + "NodeShape"),
    TARGETCLASS(Namespace.SHACL + "targetClass"),
    NODE(Namespace.SHACL + "node"),
    ORDER(Namespace.SHACL + "order"),
    OR(Namespace.SHACL + "or"),
    NOT(Namespace.SHACL + "not"),
    NODE_KIND(Namespace.SHACL + "nodeKind"),
    PROPERTYSHAPE(Namespace.SHACL + "PropertyShape"),
    AND(Namespace.SHACL + "and"),
    NODES(Namespace.SHACL + "nodes"),
    TARGET_TYPE(Namespace.SHACL + "targetType"),
    TARGET(Namespace.SHACL + "target"),
    SPARQL_TARGET(Namespace.SHACL + "SPARQLTarget"),
    FUNCTION(Namespace.SHACL + "Function"),
    RETURN_TYPE(Namespace.SHACL + "returnType"),
    GROUP(Namespace.SHACL + "group"),
    NAME(Namespace.SHACL + "name"),
    EXPRESSION(Namespace.SHACL + "expression"),
    HAS_VALUE(Namespace.SHACL + "hasValue"),
    ;

    private final String value;

    SHACL(final String value) {
        this.value = value;
    }

    SHACL(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static SHACL from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (SHACL b : SHACL.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
