// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum SHACL implements VocabEnum {

    NAMESPACE("http://www.w3.org/ns/shacl#"),
    PREFIX("sh"),
    PATH(SHACL.NAMESPACE + "path"),
    MININCLUSIVE(SHACL.NAMESPACE + "minInclusive"),
    MINEXCLUSIVE(SHACL.NAMESPACE + "minExclusive"),
    MAXINCLUSIVE(SHACL.NAMESPACE + "maxInclusive"),
    MAXEXCLUSIVE(SHACL.NAMESPACE + "maxExclusive"),
    PROPERTY(SHACL.NAMESPACE + "property"),
    PROPERTY_GROUP(SHACL.NAMESPACE + "PropertyGroup"),
    MINCOUNT(SHACL.NAMESPACE + "minCount"),
    MAXCOUNT(SHACL.NAMESPACE + "maxCount"),
    VALUE(SHACL.NAMESPACE + "value"),
    PATTERN(SHACL.NAMESPACE + "pattern"),
    INVERSEPATH(SHACL.NAMESPACE + "inversePath"),
    CLASS(SHACL.NAMESPACE + "class"),
    DATATYPE(SHACL.NAMESPACE + "datatype"),
    SPARQL(SHACL.NAMESPACE + "sparql"),
    SELECT(SHACL.NAMESPACE + "select"),
    PARAMETER(SHACL.NAMESPACE + "parameter"),
    IRI(SHACL.NAMESPACE + "IRI"),
    OPTIONAL(SHACL.NAMESPACE + "optional"),
    NODESHAPE(SHACL.NAMESPACE + "NodeShape"),
    TARGETCLASS(SHACL.NAMESPACE + "targetClass"),
    NODE(SHACL.NAMESPACE + "node"),
    ORDER(SHACL.NAMESPACE + "order"),
    OR(SHACL.NAMESPACE + "or"),
    NOT(SHACL.NAMESPACE + "not"),
    NODE_KIND(SHACL.NAMESPACE + "nodeKind"),
    PROPERTYSHAPE(SHACL.NAMESPACE + "PropertyShape"),
    AND(SHACL.NAMESPACE + "and"),
    NODES(SHACL.NAMESPACE + "nodes"),
    TARGET_TYPE(SHACL.NAMESPACE + "targetType"),
    TARGET(SHACL.NAMESPACE + "target"),
    SPARQL_TARGET(SHACL.NAMESPACE + "SPARQLTarget"),
    FUNCTION(SHACL.NAMESPACE + "Function"),
    RETURN_TYPE(SHACL.NAMESPACE + "returnType"),
    GROUP(SHACL.NAMESPACE + "group"),
    NAME(SHACL.NAMESPACE + "name"),
    EXPRESSION(SHACL.NAMESPACE + "expression"),
    HAS_VALUE(SHACL.NAMESPACE + "hasValue"),
    ;

    private final String value;

    SHACL(final String value) {
        this.value = value;
    }

    SHACL(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static SHACL from(String text) {
    for (SHACL b : SHACL.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
