// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum USER implements VocabEnum {

    DOMAIN("http://endhealth.info/"),
    PREFIX("usr"),
    USER_PRESET(USER.DOMAIN + "UserPreset"),
    USER_PRIMARY_COLOR(USER.DOMAIN + "UserPrimaryColor"),
    USER_SURFACE_COLOR(USER.DOMAIN + "UserSurfaceColor"),
    USER_DARK_MODE(USER.DOMAIN + "UserDarkMode"),
    USER_SCALE(USER.DOMAIN + "UserScale"),
    USER_MRU(USER.DOMAIN + "UserMRU"),
    USER_FAVOURITES(USER.DOMAIN + "UserFavourites"),
    ORGANISATIONS(USER.DOMAIN + "ORGANISATIONS"),
    ;

    private final String value;

    USER(final String value) {
        this.value = value;
    }

    USER(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static USER from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (USER b : USER.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
