// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum VALIDATION implements VocabEnum {

    DOMAIN("http://endhealth.info/im#"),
    NAMESPACE(VALIDATION.DOMAIN + "Validation_"),
    IS_DEFINITION(VALIDATION.NAMESPACE + "isDefinition"),
    HAS_PARENT(VALIDATION.NAMESPACE + "hasParent"),
    IS_IRI(VALIDATION.NAMESPACE + "isIri"),
    IS_TERMCODE(VALIDATION.NAMESPACE + "isTermcode"),
    IS_PROPERTY(VALIDATION.NAMESPACE + "isProperty"),
    IS_SCHEME(VALIDATION.NAMESPACE + "isScheme"),
    IS_STATUS(VALIDATION.NAMESPACE + "isStatus"),
    IS_ROLE_GROUP(VALIDATION.NAMESPACE + "isRoleGroup"),
    ;

    private final String value;

    VALIDATION(final String value) {
        this.value = value;
    }

    VALIDATION(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static VALIDATION from(String text) {
    for (VALIDATION b : VALIDATION.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
