// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum WORKFLOW implements VocabEnum {

    DOMAIN("http://endhealth.info/"),
    BUG_REPORT(Namespace.WORKFLOW + "bugReport"),
    DATE_CREATED(Namespace.WORKFLOW + "dateCreated"),
    CREATED_BY(Namespace.WORKFLOW + "createdBy"),
    ASSIGNED_TO(Namespace.WORKFLOW + "assignedTo"),
    STATE(Namespace.WORKFLOW + "state"),
    HOST_URL(Namespace.WORKFLOW + "hostUrl"),
    RELATED_PRODUCT(Namespace.WORKFLOW + "relatedProduct"),
    RELATED_MODULE(Namespace.WORKFLOW + "relatedModule"),
    OPERATING_SYSTEM(Namespace.WORKFLOW + "operatingSystem"),
    OPERATING_SYSTEM_OTHER(Namespace.WORKFLOW + "operatingSystemOther"),
    BROWSER(Namespace.WORKFLOW + "browser"),
    BROWSER_OTHER(Namespace.WORKFLOW + "browserOther"),
    SEVERITY(Namespace.WORKFLOW + "severity"),
    ERROR(Namespace.WORKFLOW + "errorDetails"),
    REPRODUCE_STEPS(Namespace.WORKFLOW + "reproduceSteps"),
    EXPECTED_RESULT(Namespace.WORKFLOW + "expectedResult"),
    ACTUAL_RESULT(Namespace.WORKFLOW + "actualResult"),
    RELATED_VERSION(Namespace.WORKFLOW + "relatedVersion"),
    REQUESTED_ROLE(Namespace.WORKFLOW + "requestedRole"),
    APPROVAL_TYPE(Namespace.WORKFLOW + "approvalType"),
    HISTORY(Namespace.WORKFLOW + "history"),
    HISTORY_PREDICATE(Namespace.WORKFLOW + "historyPredicate"),
    HISTORY_ORIGINAL_OBJECT(Namespace.WORKFLOW + "historyOriginalObject"),
    HISTORY_NEW_OBJECT(Namespace.WORKFLOW + "historyNewObject"),
    HISTORY_CHANGE_DATE(Namespace.WORKFLOW + "historyChangeDate"),
    MODIFIED_BY(Namespace.WORKFLOW + "modifiedBy"),
    ;

    private final String value;

    WORKFLOW(final String value) {
        this.value = value;
    }

    WORKFLOW(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static WORKFLOW from(String text) {
      if (text == null)
        throw new IllegalArgumentException("no text specified");

      for (WORKFLOW b : WORKFLOW.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("no enums match text specified");
    }

}
