// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum WORKFLOW implements VocabEnum {

    DOMAIN("http://endhealth.info/"),
    NAMESPACE(WORKFLOW.DOMAIN + "workflow#"),
    BUG_REPORT(WORKFLOW.NAMESPACE + "bugReport"),
    DATE_CREATED(WORKFLOW.NAMESPACE + "dateCreated"),
    CREATED_BY(WORKFLOW.NAMESPACE + "createdBy"),
    ASSIGNED_TO(WORKFLOW.NAMESPACE + "assignedTo"),
    STATE(WORKFLOW.NAMESPACE + "state"),
    HOST_URL(WORKFLOW.NAMESPACE + "hostUrl"),
    RELATED_PRODUCT(WORKFLOW.NAMESPACE + "relatedProduct"),
    RELATED_MODULE(WORKFLOW.NAMESPACE + "relatedModule"),
    OPERATING_SYSTEM(WORKFLOW.NAMESPACE + "operatingSystem"),
    OPERATING_SYSTEM_OTHER(WORKFLOW.NAMESPACE + "operatingSystemOther"),
    BROWSER(WORKFLOW.NAMESPACE + "browser"),
    BROWSER_OTHER(WORKFLOW.NAMESPACE + "browserOther"),
    SEVERITY(WORKFLOW.NAMESPACE + "severity"),
    ERROR(WORKFLOW.NAMESPACE + "errorDetails"),
    REPRODUCE_STEPS(WORKFLOW.NAMESPACE + "reproduceSteps"),
    EXPECTED_RESULT(WORKFLOW.NAMESPACE + "expectedResult"),
    ACTUAL_RESULT(WORKFLOW.NAMESPACE + "actualResult"),
    RELATED_VERSION(WORKFLOW.NAMESPACE + "relatedVersion"),
    REQUESTED_ROLE(WORKFLOW.NAMESPACE + "requestedRole"),
    APPROVAL_TYPE(WORKFLOW.NAMESPACE + "approvalType"),
    HISTORY(WORKFLOW.NAMESPACE + "history"),
    HISTORY_PREDICATE(WORKFLOW.NAMESPACE + "historyPredicate"),
    HISTORY_ORIGINAL_OBJECT(WORKFLOW.NAMESPACE + "historyOriginalObject"),
    HISTORY_NEW_OBJECT(WORKFLOW.NAMESPACE + "historyNewObject"),
    HISTORY_CHANGE_DATE(WORKFLOW.NAMESPACE + "historyChangeDate"),
    MODIFIED_BY(WORKFLOW.NAMESPACE + "modifiedBy"),
    ;

    private final String value;

    WORKFLOW(final String value) {
        this.value = value;
    }

    WORKFLOW(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static WORKFLOW from(String text) {
    for (WORKFLOW b : WORKFLOW.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
