// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum XSD implements VocabEnum {

    NAMESPACE("http://www.w3.org/2001/XMLSchema#"),
    PREFIX("xsd"),
    PATTERN(XSD.NAMESPACE + "pattern"),
    MIN_INCLUSIVE(XSD.NAMESPACE + "minInclusive"),
    MIN_EXCLUSIVE(XSD.NAMESPACE + "minExclusive"),
    MAX_INCLUSIVE(XSD.NAMESPACE + "maxInclusive"),
    MAX_EXCLUSIVE(XSD.NAMESPACE + "maxExclusive"),
    INTEGER(XSD.NAMESPACE + "integer"),
    STRING(XSD.NAMESPACE + "string"),
    BOOLEAN(XSD.NAMESPACE + "boolean"),
    LONG(XSD.NAMESPACE + "long"),
    DOUBLE(XSD.NAMESPACE + "double"),
    DATE_TIME(XSD.NAMESPACE + "dateTime"),
    NUMBER(XSD.NAMESPACE + "number"),
    DECIMAL(XSD.NAMESPACE + "decimal"),
    ;

    private final String value;

    XSD(final String value) {
        this.value = value;
    }

    XSD(final VocabEnum value) {
        this.value = value.toString();
    }

    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static XSD from(String text) {
    for (XSD b : XSD.values()) {
      if (b.value.equals(text)) {
        return b;
      }
    }
    return null;
  }
}
