// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

package org.endeavourhealth.imapi.vocabulary;

import com.fasterxml.jackson.annotation.JsonValue;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.endeavourhealth.imapi.model.tripletree.TTIriRef;

import java.util.Arrays;
import java.util.stream.Collectors;

import static org.endeavourhealth.imapi.model.tripletree.TTIriRef.iri;

public enum XSD implements VocabEnum {

    PREFIX("xsd"),
    PATTERN(Namespace.XSD + "pattern"),
    MIN_INCLUSIVE(Namespace.XSD + "minInclusive"),
    MIN_EXCLUSIVE(Namespace.XSD + "minExclusive"),
    MAX_INCLUSIVE(Namespace.XSD + "maxInclusive"),
    MAX_EXCLUSIVE(Namespace.XSD + "maxExclusive"),
    INTEGER(Namespace.XSD + "integer"),
    STRING(Namespace.XSD + "string"),
    BOOLEAN(Namespace.XSD + "boolean"),
    LONG(Namespace.XSD + "long"),
    DOUBLE(Namespace.XSD + "double"),
    DATE_TIME(Namespace.XSD + "dateTime"),
    NUMBER(Namespace.XSD + "number"),
    DECIMAL(Namespace.XSD + "decimal"),
    ;

    private final String value;

    XSD(final String value) {
        this.value = value;
    }

    XSD(final VocabEnum value) {
        this.value = value.toString();
    }

    @JsonValue
    @Override
    public String toString() {
        return value;
    }

    public TTIriRef asIri() {
      return iri(
        value,
        Arrays.stream(this.name().split("_"))
          .map(i -> i.substring(0, 1).toUpperCase() + i.substring(1).toLowerCase())
          .collect(Collectors.joining(" "))
      );
    }

    public IRI asDbIri() {
      return Values.iri(value);
    }

    public static XSD from(String text) {
      if (text == null)
        return null;

      for (XSD b : XSD.values()) {
        if (b.value.equals(text)) {
          return b;
        }
      }
      return null;
    }

}
