POST http://localhost:8080/api/query/public/queryIM
Content-Type: application/json

{
  "query" : {
    "name" : "Some Barts cerner codes from context including a regex",
    "where" : {
      "property" : {
        "@id" : "http://endhealth.info/im#sourceContext"
      },
      "where" : {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceRegex"
        }
      }
    },
    "select" : [ {
      "property" : {
        "@id" : "http://www.w3.org/2000/01/rdf-schema#label"
      }
    }, {
      "property" : {
        "@id" : "http://endhealth.info/im#code"
      }
    }, {
      "property" : {
        "@id" : "http://endhealth.info/im#sourceContext"
      },
      "select" : [ {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceCodeScheme"
        }
      }, {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceHeading"
        }
      }, {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceSystem"
        }
      }, {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceTable"
        }
      }, {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceField"
        }
      }, {
        "property" : {
          "@id" : "http://endhealth.info/im#sourceSchema"
        }
      } ]
    } ],
    "usePrefixes" : true
  }
}
